export interface CreateSupplierDetailServicesInput { 
  Vehicle_type: string,
  Vehicle_brand: string, 
  Type_service:string,
  Vehicle_model: string, 
  Doors:string,
  Seats:string,
  Category_space:string,
  Max_number_pax_accommodate:string,
  Luggage_information:string,
  Max_number_medium_suitcase:string,
  Max_number_carbin_bag:string, 
  Space_available_other_luggage:string, 
  Location_details:string,
  Transfer_information:string,
  Service_providing_location:string,  
  Airport:string,
  Port_cruise:string, 
  Station:string,
  City_center:string,
  Vehicle_for:string,
  Half_day_city_limit_4hrs: string, 
  Full_day_city_limit_8hrs: string,   
  Inclusions:string,
  Vehicle_rent:string,
  Fuel:string,
  Driver:string,
  Parking_fees:string,
  Toll_or_taxes:string, 
  Driver_tips:string,
  Other:string, 
  } 